FROM python:3.9-slim

WORKDIR /app

COPY requirements_inference.txt .
RUN pip install --no-cache-dir -r requirements_inference.txt

COPY inference.py .
COPY prometheus_exporter.py .

EXPOSE 8000

CMD ["uvicorn", "inference:app", "--host", "0.0.0.0", "--port", "8000"]
